Remove redundant regexp
Shopify/liquid pull request #1540
Opened 2022-03-12 10:20 UTC by Watson1978

The same processing is possible without using regular expressions.

−               | before   | after   | result
--               | --       | --      | --
parse            | 61.006   | 61.975  | 1.016x
render           | 197.095  | 197.103 | -
parse & render   | 44.846   | 45.180  | 1.008x

### Environment
- MacBook Pro (14 inch, 2021)
- macOS 12.3 beta
- Apple M1 Max
- Ruby 3.0.3

### Before
```
$ ruby benchmark.rb

Running benchmark for 10 seconds (with 5 seconds warmup).

Warming up --------------------------------------
              parse:     6.000  i/100ms
             render:    19.000  i/100ms
     parse & render:     4.000  i/100ms
Calculating -------------------------------------
              parse:     61.006  (± 0.0%) i/s -    612.000  in  10.032337s
             render:    197.095  (± 1.5%) i/s -      1.976k in  10.027538s
     parse & render:     44.846  (± 2.2%) i/s -    452.000  in  10.080806s
```

### After
```
$ ruby benchmark.rb

Running benchmark for 10 seconds (with 5 seconds warmup).

Warming up --------------------------------------
              parse:     6.000  i/100ms
             render:    19.000  i/100ms
     parse & render:     4.000  i/100ms
Calculating -------------------------------------
              parse:     61.975  (± 0.0%) i/s -    624.000  in  10.069036s
             render:    197.103  (± 1.0%) i/s -      1.976k in  10.026615s
     parse & render:     45.180  (± 0.0%) i/s -    452.000  in  10.005335s
```

2022-03-15 18:39 UTC, macournoyer requested changes
I don't think `token.strip` is a good idea. If you revert this change, rest looks good to me.

2022-03-15 18:39 UTC, macournoyer commented on lib/liquid/block_body.rb
> +        unless token.strip.empty?
This will cause an allocation. I'm not sure the the minimal perf gain justifies this.

2022-03-15 18:39 UTC, macournoyer commented on lib/liquid/block_body.rb
> +        unless token.strip.empty?
This will cause an allocation. I'm not sure the the minimal perf gain justifies this.

2022-03-15 18:39 UTC, macournoyer commented on lib/liquid/variable_lookup.rb
> +      if name&.start_with?('[') && name&.end_with?(']')
I suspect the perf gain is only due to this (and bellow). This looks like a nice optimization to me.

2022-03-15 18:39 UTC, macournoyer commented on lib/liquid/variable_lookup.rb
> +      if name&.start_with?('[') && name&.end_with?(']')
I suspect the perf gain is only due to this (and bellow). This looks like a nice optimization to me.

2022-03-16 03:46 UTC, Watson1978 commented
> I don't think token.strip is a good idea. If you revert this change, rest looks good to me.

OK, reverted at https://github.com/Shopify/liquid/pull/1540/commits/22568080b1cb6f19969d55d68dc39b5c04a37b17

However, I think it should use `String#match?` instead because it doesn't use backreference of `String#=~`. 
See https://github.com/Shopify/liquid/pull/1540/commits/fad58ef436bb9a516ea8364d9398cb6f6876d784

2022-03-16 17:24 UTC, macournoyer approved these changes
Thanks a lot! That's awesome 🙏

2022-03-22 18:52 UTC, merged